# Generated by Django 5.2.6 on 2025-12-24 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('file_name', models.CharField(max_length=255, verbose_name='文件名称')),
                ('file_uuid', models.CharField(max_length=255, unique=True, verbose_name='文件uuid')),
                ('status', models.IntegerField(choices=[(0, '排队中'), (1, '审核中'), (2, '审核成功'), (3, '审核失败')], db_comment='0-排队中, 1-审核中, 2-审核成功, 3-审核失败', default=0, help_text='0-排队中, 1-审核中, 2-审核成功, 3-审核失败')),
            ],
            options={
                'db_table': 'doc',
            },
        ),
        migrations.CreateModel(
            name='DocStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('parse_status', models.IntegerField(choices=[(0, '等待'), (1, '成功'), (2, '失败')], db_comment='状态: 0-等待, 1-成功, 2-失败', default=0)),
                ('parse_start', models.DateTimeField(db_comment='解析开始时间', null=True)),
                ('parse_end', models.DateTimeField(db_comment='解析完成时间', null=True)),
                ('text_review_status', models.IntegerField(choices=[(0, '等待'), (1, '成功'), (2, '失败')], db_comment='状态: 0-等待, 1-成功, 2-失败', default=0)),
                ('text_review_start', models.DateTimeField(db_comment='文字纠错开始时间', null=True)),
                ('text_review_end', models.DateTimeField(db_comment='文字纠错结束时间', null=True)),
                ('financial_review_status', models.IntegerField(choices=[(0, '等待'), (1, '成功'), (2, '失败')], db_comment='状态: 0-等待, 1-成功, 2-失败', default=0)),
                ('financial_review_start', models.DateTimeField(db_comment='财务审核开始时间', null=True)),
                ('financial_review_end', models.DateTimeField(db_comment='财务审核完成时间', null=True)),
            ],
            options={
                'db_table': 'doc_status',
            },
        ),
    ]
