# Generated by Django 5.2.6 on 2025-12-24 06:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doc', '0001_initial'),
        ('project', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doc', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='doc',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doc', to='project.project', verbose_name='项目id'),
        ),
        migrations.AddField(
            model_name='docstatus',
            name='doc',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doc_status', to='doc.doc'),
        ),
        migrations.AddIndex(
            model_name='doc',
            index=models.Index(fields=['project_id', 'is_deleted'], name='doc_project_371ffc_idx'),
        ),
    ]
