from django.contrib.auth.models import AbstractUser
from django.db import models
from api.app.base.models import BaseModel


class User(AbstractUser):
    nickname = models.CharField(max_length=255, blank=True, null=True, help_text="User nickname")
    is_deleted = models.BooleanField(default=False, help_text="Whether the user is deleted", db_comment="Whether the user is deleted")
    # Important: Override the groups field in AbstractUser to point to custom Group
    groups = models.ManyToManyField(
        'Group',  # Point to the custom Group model
        blank=True,
        help_text='User groups the user belongs to',
        related_name='user_groups',
        related_query_name='user',
    )

    class Meta:
        db_table = "users"
        verbose_name = "User"
        verbose_name_plural = "User Management"


class Group(BaseModel):
    name = models.CharField(max_length=32, help_text="User group name")
    description = models.CharField(null=True, blank=True, max_length=255, help_text="User group description")

    class Meta:
        # The auth_group table generated by Django itself still exists, but it has no effect
        db_table = "groups"
        verbose_name = "User Group"
        verbose_name_plural = "User Group Management"

    def __str__(self):
        return self.name
