# Generated by Django 5.2.6 on 2025-12-24 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('origin_text', models.CharField(db_comment='原文', max_length=255)),
                ('correct_text', models.CharField(db_comment='修改建议', max_length=255)),
                ('pos_list', models.JSONField(db_comment='位置列表', default=list)),
                ('doc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doc_financial_error', to='doc.doc', verbose_name='项目id')),
            ],
            options={
                'db_table': 'financial_error',
            },
        ),
        migrations.CreateModel(
            name='TextError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('origin_text', models.CharField(db_comment='原文', max_length=255)),
                ('correct_text', models.CharField(db_comment='修改建议', max_length=255)),
                ('pos_list', models.JSONField(db_comment='位置列表', default=list)),
                ('page_id', models.IntegerField(db_comment='所在页码数')),
                ('cross_page', models.BooleanField(db_comment='是否跨页', default=False)),
                ('doc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doc_text_error', to='doc.doc', verbose_name='项目id')),
            ],
            options={
                'db_table': 'text_error',
            },
        ),
    ]
