# Generated by Django 5.2.6 on 2026-01-27 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('error', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialerror',
            name='status',
            field=models.IntegerField(choices=[(0, '排队中'), (1, '审核中'), (2, '审核成功'), (3, '审核失败')], db_comment='0-错误, 1-疑似错误, 2-正确', default=0, help_text='0-错误, 1-疑似错误, 2-正确'),
        ),
        migrations.AddField(
            model_name='financialerror',
            name='type',
            field=models.CharField(db_comment='类型', default='formula', max_length=50),
        ),
    ]
