# Generated by Django 5.2.6 on 2026-01-27 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('error', '0002_financialerror_status_financialerror_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialerror',
            name='cross_page',
            field=models.BooleanField(db_comment='是否跨页', default=False),
        ),
        migrations.AddField(
            model_name='financialerror',
            name='page_id',
            field=models.IntegerField(db_comment='所在页码数', default=0),
        ),
        migrations.AlterField(
            model_name='financialerror',
            name='status',
            field=models.IntegerField(choices=[(0, '错误'), (1, '疑似错误'), (2, '正确')], db_comment='0-错误, 1-疑似错误, 2-正确', default=0, help_text='0-错误, 1-疑似错误, 2-正确'),
        ),
    ]
