# Generated by Django 5.2.6 on 2026-01-27 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('error', '0003_financialerror_cross_page_financialerror_page_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialerror',
            name='formula',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='financialerror',
            name='formula_value',
            field=models.TextField(default=''),
        ),
    ]
