# Generated by Django 5.2.6 on 2026-01-28 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('error', '0005_financialerror_formula_result_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialerror',
            name='formula_breakdown',
            field=models.JSONField(db_comment='公式拆解,供前端使用', default=list, verbose_name='公式拆解,供前端使用'),
        ),
        migrations.AlterField(
            model_name='financialerror',
            name='correct_text',
            field=models.CharField(db_comment='修改建议', max_length=255, verbose_name='公式计算的结果'),
        ),
        migrations.AlterField(
            model_name='financialerror',
            name='formula',
            field=models.TextField(default='', verbose_name='计算公式'),
        ),
        migrations.AlterField(
            model_name='financialerror',
            name='formula_result_name',
            field=models.TextField(default='', verbose_name='计算结果对应的财务科目'),
        ),
        migrations.AlterField(
            model_name='financialerror',
            name='formula_value',
            field=models.TextField(default='', verbose_name='带入数值后计算公式'),
        ),
        migrations.AlterField(
            model_name='financialerror',
            name='origin_text',
            field=models.CharField(db_comment='原文', max_length=255, verbose_name='文件表格中的结果'),
        ),
        migrations.AlterField(
            model_name='financialerror',
            name='type',
            field=models.CharField(db_comment='类型', default='formula', max_length=50, verbose_name='错误类型；<br/>accounting_formula-财务审核错误（勾稽关系错误）<br/>accounting_consistency-财务审核错误（数据填报错误）'),
        ),
    ]
