# Generated by Django 5.2.6 on 2026-03-03 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('error', '0006_financialerror_formula_breakdown_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialerror',
            name='report_period',
            field=models.CharField(db_comment='报告期', default='', max_length=255, verbose_name='报告期'),
        ),
    ]
