# Generated by Django 5.2.6 on 2026-03-03 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('error', '0007_financialerror_report_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialerror',
            name='table_title',
            field=models.CharField(db_comment='文件中的表名', default='', max_length=255, verbose_name='文件中的表名'),
        ),
    ]
