# Generated by Django 5.2.6 on 2025-12-24 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LLMProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('name', models.CharField(max_length=64, verbose_name='名称')),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='温度值')),
                ('frequency_penalty', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='惩罚频率')),
                ('top_p', models.PositiveIntegerField(verbose_name='TopP')),
                ('chunk_length', models.PositiveIntegerField(verbose_name='token 长度')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('url', models.URLField(verbose_name='调用地址')),
                ('headers', models.JSONField(blank=True, default=dict, verbose_name='请求头')),
                ('is_active', models.BooleanField(default=False, verbose_name='是否激活')),
            ],
            options={
                'db_table': 'llm_provider',
                'ordering': ['create_time'],
            },
        ),
        migrations.CreateModel(
            name='LLMTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('status', models.IntegerField(choices=[(0, '排队中'), (1, '审核中'), (2, '审核成功'), (3, '审核失败')], db_comment='0-排队中, 1-审核中, 2-审核成功, 3-审核失败', default=0, help_text='0-排队中, 1-审核中, 2-审核成功, 3-审核失败')),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='温度值')),
                ('frequency_penalty', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='惩罚频率')),
                ('top_p', models.PositiveIntegerField(verbose_name='TopP')),
                ('chunk_length', models.PositiveIntegerField(verbose_name='token 长度')),
                ('hit_rate', models.FloatField(blank=True, null=True, verbose_name='检出率')),
                ('precision', models.FloatField(blank=True, null=True, verbose_name='准确率')),
                ('recall', models.FloatField(blank=True, null=True, verbose_name='召回率')),
                ('duration', models.FloatField(blank=True, null=True, verbose_name='审核时长')),
            ],
            options={
                'db_table': 'llm_test_history',
                'ordering': ['create_time'],
            },
        ),
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('name', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('is_active', models.BooleanField(default=False, verbose_name='是否激活')),
            ],
            options={
                'db_table': 'llm_prompt',
                'ordering': ['create_time'],
            },
        ),
        migrations.CreateModel(
            name='TestSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('uid', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='业务唯一号')),
                ('input', models.TextField(verbose_name='输入文本')),
                ('gold', models.TextField(verbose_name='标准答案')),
            ],
            options={
                'db_table': 'llm_test_sample',
            },
        ),
    ]
