# Generated by Django 5.2.6 on 2025-12-24 06:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('llm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='llmprovider',
            name='creator',
            field=models.ForeignKey(db_column='creator_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llm_provider', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='llmtest',
            name='creator',
            field=models.ForeignKey(db_column='creator_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llm_test', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='llmtest',
            name='provider',
            field=models.ForeignKey(db_column='provider_id', on_delete=django.db.models.deletion.CASCADE, to='llm.llmprovider', verbose_name='大模型供应商'),
        ),
        migrations.AddField(
            model_name='prompt',
            name='creator',
            field=models.ForeignKey(db_column='creator_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promote', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='llmtest',
            name='prompt',
            field=models.ForeignKey(db_column='prompt_id', on_delete=django.db.models.deletion.CASCADE, to='llm.prompt', verbose_name='提示词'),
        ),
        migrations.AddField(
            model_name='testsample',
            name='creator',
            field=models.ForeignKey(db_column='creator_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llm_test_sample', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
    ]
