# Generated by Django 5.2.6 on 2025-12-29 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmtest',
            name='top_p',
            field=models.IntegerField(verbose_name='TopP'),
        ),
    ]
