# Generated by Django 5.2.6 on 2025-12-29 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0003_alter_llmtest_top_p'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmtest',
            name='prompt_content_snapshot',
            field=models.TextField(default='', verbose_name='提示词内容快照'),
            preserve_default=False,
        ),
    ]
