# Generated by Django 5.2.6 on 2025-12-30 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0004_llmtest_prompt_content_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmtest',
            name='system_default',
            field=models.BooleanField(default=False, verbose_name='系统默认'),
        ),
    ]
