# Generated by Django 5.2.6 on 2026-01-06 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0005_llmtest_system_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmtest',
            name='status',
            field=models.IntegerField(choices=[(0, '排队中'), (1, '审核中'), (2, '审核成功'), (3, '审核失败')], db_comment='0-测试中, 2-测试成功, 3-测试失败', default=0, help_text='0-测试中, 2-测试成功, 3-测试失败'),
        ),
        migrations.AlterField(
            model_name='llmtest',
            name='top_p',
            field=models.FloatField(verbose_name='TopP'),
        ),
    ]
