# Generated by Django 5.2.6 on 2026-01-06 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0006_alter_llmtest_status_alter_llmtest_top_p'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='llmprovider',
            name='headers',
        ),
        migrations.RemoveField(
            model_name='llmprovider',
            name='url',
        ),
        migrations.AddField(
            model_name='llmprovider',
            name='config',
            field=models.JSONField(blank=True, default=dict, verbose_name='大模型配置'),
        ),
    ]
