# Generated by Django 5.2.6 on 2026-01-06 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0007_remove_llmprovider_headers_remove_llmprovider_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='llmprovider',
            name='chunk_length',
        ),
        migrations.RemoveField(
            model_name='llmprovider',
            name='frequency_penalty',
        ),
        migrations.RemoveField(
            model_name='llmprovider',
            name='temperature',
        ),
        migrations.RemoveField(
            model_name='llmprovider',
            name='top_p',
        ),
    ]
