# Generated by Django 5.2.6 on 2026-01-09 05:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0008_remove_llmprovider_chunk_length_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmprovider',
            name='chunk_length',
            field=models.PositiveIntegerField(default=512, verbose_name='token 长度'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='llmprovider',
            name='frequency_penalty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='惩罚频率'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='llmprovider',
            name='temperature',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='温度值'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='llmprovider',
            name='top_p',
            field=models.PositiveIntegerField(default=1, verbose_name='TopP'),
            preserve_default=False,
        ),
    ]
