# Generated by Django 5.2.6 on 2026-01-09 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0009_llmprovider_chunk_length_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmprovider',
            name='top_p',
            field=models.DecimalField(decimal_places=2, max_digits=3, verbose_name='TopP'),
        ),
    ]
