# Generated by Django 5.2.6 on 2025-12-24 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('name', models.CharField(db_comment='项目名称', max_length=255, verbose_name='项目名称')),
                ('project_type', models.IntegerField(choices=[(0, '私有项目'), (1, '公开项目')], db_comment='0-私有项目, 1-公开项目', default=1)),
            ],
            options={
                'db_table': 'project',
            },
        ),
    ]
